title: Westerveld Bouw
description: "De fundering voor een goede verbouwing"
baseurl: "/westerveldbouw"
url: "https://dschafrat.github.io"

collections:
  projects:
    output: true
    permalink: /portfolio/:name/

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"

include: ["_pages"]

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
